security:
  enable_authenticator_manager: true
  password_hashers:
    GridCP\Entity\User: 'auto'
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: 'auto'
      cost: 15
  providers:
    app_user_provider:
      entity:
        class: GridCP\Security\Common\Infrastructure\DB\MySQL\Entity\AuthEntity
        property: uuid
  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      entry_point: jwt
      json_login:
        check_path: /api/login_check
        provider: app_user_provider
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt:

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider

  access_control:
      - { path: ^/api/auth/register, roles: PUBLIC_ACCESS  }
      - { path: ^/api/login, roles: PUBLIC_ACCESS  }
      - { path: ^/api/(login|token/refresh), roles: PUBLIC_ACCESS }
      - { path: ^/api/healthcheck, roles: PUBLIC_ACCESS }
      - { path: ^/api/doc, roles: PUBLIC_ACCESS }
      - { path: ^/api/v1/ip4/subnet, roles: ROLE_USER }
      - { path: ^/api/v1/ip4/subnet, roles: ROLE_ADMIN }
      - { path: ^/api/v1/ip4, roles: ROLE_USER }
      - { path: ^/api/v1/ip4, roles: ROLE_ADMIN }
      - { path: ^/api/v1/ip4_range, roles: ROLE_USER }
      - { path: ^/api/v1/ip4_network, roles: ROLE_USER }
      - { path: ^/api/v1/ip4_tag, roles: PUBLIC_ACCESS }
      - { path: ^/api/v1/float_group, roles: ROLE_USER }
      - { path: ^/api/v1/node, roles: ROLE_USER }
      - { path: ^/api/v1/proxmox, roles: ROLE_USER }
      - { path: ^/api/v1/pve/vm, roles: ROLE_USER }
      - { path: ^/api/v1/auth/change/password, roles: ROLE_USER}
      - { path: ^/api/v1/device, roles: IS_AUTHENTICATED_FULLY }
      #- { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }